SELECT GETDATE() [GETDATE()]
SELECT CURRENT_TIMESTAMP [CURRENT_TIMESTAMP]
SELECT SYSDATETIME() [SYSDATETIME()]
SELECT SYSDATETIMEOFFSET() [SYSDATETIMEOFFSET()]
SELECT GETUTCDATE() [GETUTCDATE()]

SELECT DAY('01/11/2017')
SELECT DAY('2017-01-11')