-- DELETE FROM Customers where CustomerId < 124


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRAN

PRINT 'Hello World :: ' + CONVERT(VARCHAR, GETUTCDATE(), 126)
SELECT * FROM Customers 

WAITFOR DELAY '00:00:7';

PRINT 'Hello World :: ' + CONVERT(VARCHAR, GETUTCDATE(), 126)
SELECT * FROM Customers 

COMMIT TRAN


