BEGIN TRY
	
	BEGIN TRAN Tx1

	INSERT INTO Customers VALUES ('Oranges-' + CAST(GETDATE() AS VARCHAR))

	UPDATE Customers SET CustomerName = 'Changed-' + CAST(GETDATE() AS VARCHAR) WHERE CustomerId = SCOPE_IDENTITY() - 1
	
	COMMIT TRAN Tx1
	PRINT 'Commit :: ' + CONVERT(VARCHAR, GETUTCDATE(), 126)
		
END TRY
BEGIN CATCH
	ROLLBACK TRAN Tx1	
	PRINT 'Rollback'
END CATCH


